from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path(
        'api/v1/lowlevel/posts/<int:pk>/',
        views.APIPostDetailLowLevel.as_view()
    ),
    path(
        'api/v1/lowlevel/posts/',
        views.APIPostLowLevel.as_view()
    ),
    path(
        'api/v1/highlevel/posts/',
        views.APIPostList.as_view()
    ),
    path(
        'api/v1/highlevel/posts/<int:pk>/',
        views.APIPostDetail.as_view()
    ),
    path(
        '',
        views.PostListView.as_view(),
        name='index'
    ),
    path(
        'posts/create/',
        views.PostCreateView.as_view(),
        name='create_post'
    ),
    path(
        'profile/edit/',
        views.ProfileUpdateView.as_view(),
        name='edit_profile'
    ),
    path(
        'profile/<slug:username>/',
        views.ProfileListView.as_view(),
        name='profile'
    ),
    path(
        'posts/<int:pk>/',
        views.PostDetailView.as_view(),
        name='post_detail'
    ),
    path(
        'posts/<int:pk>/comment/',
        views.CommentCreateView.as_view(),
        name='add_comment'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.PostUpdateView.as_view(),
        name='edit_post'
    ),
    path(
        'posts/<int:post_id>/edit_comment/<int:pk>/',
        views.CommentUpdateView.as_view(),
        name='edit_comment'
    ),
    path(
        'posts/<int:post_id>/delete_comment/<int:pk>/',
        views.CommentDeleteView.as_view(),
        name='delete_comment'
    ),
    path(
        'posts/<int:post_id>/delete/',
        views.PostDeleteView.as_view(),
        name='delete_post'
    ),
    path(
        'category/<slug:category_slug>/',
        views.PostCategoryListView.as_view(),
        name='category_posts'
    ),
]
